### PR TITLE
Fix vibrating windows

### PR DESCRIPTION
**Pull request by ghost**
Some windows with just the right amount of scrollable content would trigger the
removal of the bottom margin, however the new layout pass would show that the
content is no longer scrollable so the bottom margin would be reenabled.
This would cause the window to continously vibrate up and down.

This fix verifies the available space before adding the margin, and doesn't
add it, if it would cause the content to scroll.

### CODE REVIEW

**Comment by afollestad** [comment]
Release 0.5.9 is now available

**Comment by hzsweers** [comment]
This doesn't seem to have fixed it for me, I still see the vibration on lists that are slightly larger than the available space.

**Comment by hzsweers** [comment]
Also items don't seem to be focusable when the hitter is occurring. The click is registered, but the item view doesn't update, nor is there any ripple :frowning:

**Comment by afollestad** [comment]
@hzsweers @teslacoil https://github.com/afollestad/material-dialogs/issues/175

**Comment by afollestad** [comment]
@hzsweers I figured out why there's no selector. Before it was explicitly set to the list item layout backgrounds. I removed that because I thought they were set via code. Now that I was going through and adding customizable selectors, I found and fixed the issue.

**Comment by hzsweers** [comment]
Well it wasn't just the selector. It wouldn't update the item to be marked
as "clicked" either :/

Any luck with the jiggly windows?

**Comment by afollestad** [comment]
@hzsweers try out the latest code, it's working for me

**Pull request merged**
