### PR TITLE
add multiple mimeTypes support

### PR DESCRIPTION
**Pull request by Warrocker**
Add support for more than one mime type in FileChooserDialog

### CODE REVIEW

**Comment by afollestad** [comment]
@Warrocker looks like the build is failing

**Comment by Warrocker** [comment]
Travis logs is strange, similar it can`t find android libraries, I`ve to look what might went wrong

**Comment by afollestad** [comment]
screen shot 2017-12-05 at 12 21 39 pm

The problem is here

**Comment by Warrocker** [comment]
Thanks,  I'll fix it

**Comment by afollestad** [comment]
Version 2.0 is under development as a rewrite, so this will no longer be applicable.

**Pull request closed without merging**
