### PR TITLE
Removed setting content before checking for custom contentView

### PR DESCRIPTION
**Pull request by JasperG**
Removed setting content before checking for custom contentView.

### CODE REVIEW

**Comment by afollestad** [comment]
Why is this necessary?

**Comment by JasperG** [comment]
Because; A couple of lines later, .customView() may be called, which will throw an exception if content has been set.

And, on top of that, the call to customView() is in an if/else that sets content after all, if no customView is set.

**Comment by afollestad** [comment]
Good find, I must've missed that. Thanks.

**Comment by JasperG** [comment]
-- Just noticed the exact same issue in some other files. ( ex. MaterialListPreference )

Would you like me to patch?

**Comment by afollestad** [comment]
That would be great

**Pull request merged**
