### PR TITLE
Added edit text preference and list preference classes and sample code

### PR DESCRIPTION
**Pull request by marchold**
I added a couple of classes so my preference dialogs would also benefit from this library.

### CODE REVIEW

**Comment by marchold** [comment]
Cleaned up the pull request some. This should be better.

**Comment by marchold** [comment]
This pull request is good to go now. Just the 2 new classes and the example code.

**Comment by afollestad** [comment]
This looks great, thanks

**Comment by afollestad** [comment]
I cleaned up a lot of code, and switched around how the PreferenceActivity works. It now inherits ActionBarActivity so it receives the correct theming, and uses PreferenceFragments. The sample project APK is updated and will be on Google Play, and release 0.6.2.4 is now available through the Gradle dependency.

https://github.com/afollestad/material-dialogs/releases/tag/v0.6.2.4

**Comment by marchold** [comment]
Thanks!

On Wed, Feb 11, 2015 at 10:00 AM, Aidan Follestad <notifications@github.com>
wrote:

> I cleaned up a lot of code, and switched around how the PreferenceActivity
> works. It now inherits ActionBarActivity so it receives the correct
> theming, and uses PreferenceFragments. The sample project APK is updated
> and will be on Google Play, and release 0.6.2.4 is now available through
> the Gradle dependency.
>
> https://github.com/afollestad/material-dialogs/releases/tag/v0.6.2.4
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-dialogs/pull/246#issuecomment-73930207>
> .
>



-- 
/-_-_-___-___-___\

**Pull request merged**
