### PR TITLE
add bottom dialog

### PR DESCRIPTION
**Pull request by rebus007**
add dialogs from bottom,
just change gravity and dialog animations

### CODE REVIEW

**Comment by afollestad** [comment]
I don't intend to have this feature in this library.

**Comment by rebus007** [comment]
Just for curiosity, why you don't want to integrate this feature?

**Comment by afollestad** [comment]
This library's focus is specific, bottom sheet libraries should be used for this kind of thing.

**Comment by afollestad** [comment]
Also, adding a parameter to the Builder constructor is a major breaking change for everyone already using the library.

**Comment by rebus007** [comment]
For the parameter in the builder, you're right, in fact I had moved it as a method in the builder, but I have not yet pushed the change. 
For the library's focus I do not quite agree, I think the possibility of having all the customizable material dialog as bottom dialog can be very useful

**Comment by rebus007** [comment]
I have update the fork, if you want you can take a look

**Pull request closed without merging**
