### PR TITLE
Added EditText to the dialog

### PR DESCRIPTION
**Pull request by andrewlord1990**
This pull request adds an EditText to the dialog.

* Turn it on through a Builder method.
* Specify EditText hint
* Provide a default value to pre-fill the EditText with
* Set a TextWatcher on the EditText to be informed of changes to the text
* Provide a callback to be informed of the text when the positive button is pressed
* Perform input validation on the entered text
    * Provide a validator class to use
    * Specify an error message to display when the input is invalid
    * Error appears as message below the EditText, there is option to instead display it in little popup with error icon (standard EditText setError(String) method.
* EditText is tinted (color filter used for pre-Android 5).

### CODE REVIEW

**Comment by afollestad** [comment]
I didn't include this cause it seems to take away from the minimal feel. I think it works better as a custom view option.

**Comment by andrewlord1990** [comment]
Ok fair enough. Should have discussed it first before implementing!

I have lots of Text input dialogs in other projects, so thought it might be a common use-case. I noticed there was a text input dialog as part of the Edit text preference but found I couldn't use it as a generic dialog, so implemented this.

I will just use custom views to do this, like you said.

Thanks anyway!

**Comment by afollestad** [comment]
I decided it would fit in the project now that there's a progress dialog

https://github.com/afollestad/material-dialogs/commit/1ccca94bd0cac6601901f88d2a3d0c8b55f91cfe

**Comment by andrewlord1990** [comment]
Ah ok excellent. Which of the features mentioned above would you be interested in seeing? I can check out the latest code and re-implement the feature.

**Comment by afollestad** [comment]
I actually already completed the feature before I commented last night :)
this upcoming release will be huge

**Comment by andrewlord1990** [comment]
Oh okay, fair enough!

**Pull request closed without merging**
