### PR TITLE
Custom Theme Enabled

### PR DESCRIPTION
**Pull request by TheFinestArtist**
https://github.com/afollestad/material-dialogs/issues/100
Added some global attributes such as
```xml
<item name="md_custom_theme">true</item>
<item name="md_bg_color">#673AB7</item>
<item name="md_divider_color">#673AB7</item>
<item name="md_selector">@drawable/selector</item>
<item name="md_btn_selector">@drawable/selector</item>
```

New attribute ```md_bg_color```, ```md_divider_color```, ```md_selector```, ```md_btn_selector``` will be enabled only if ```md_custom_theme``` is ```true```.

We can also set new attributes programmatically.
```java
public Builder backgroundColor(int color)
public Builder backgroundColorRes(@ColorRes int colorRes)
public Builder dividerColor(int color) 
public Builder dividerColorRes(@ColorRes int colorRes)
public Builder selector(@DrawableRes int selector)
public Builder btnSelector(@DrawableRes int btnSelector)
```

If we don't set default for each attribute while using custom dialog, the default light or dark theme will be set as default. For example, when ```md_dark_theme``` is ```true``` and ```md_custom_theme``` is also ```true```, but ```md_bg_color``` hasn't set yet, the background color might follow background color of ```md_dark_theme```.

### CODE REVIEW

**Comment by afollestad** [comment]
This looks good, but `md_custom_theme` seems unnecessary

**Comment by TheFinestArtist** [comment]
@afollestad OK. I will remove ```md_custom_theme``` and let you know again

**Comment by TheFinestArtist** [comment]
@afollestad I was actually thinking the same thing about ```md_custom_theme``` attribute. I removed the attribute so that people can use all the global attribute anytime. Also updated sample app. Themed Dialog now has background color and new button selector.

**Comment by afollestad** [comment]
This looks good.

One more thing, what is this line for? The theme is already set to the Builder before this line. https://github.com/afollestad/material-dialogs/pull/152/files#diff-f3e62b50bd1b0ff34ab2d02ea80b7b78R93

**Comment by afollestad** [comment]
This is looking great, thanks!

**Comment by afollestad** [comment]
Pushed some cleanup and stuff just now. Although there's a weird bug that recently showed up with action button selectors.

**Comment by afollestad** [comment]
Hey @hzsweers, when you get the chance, you could possibly help figure out an issue that recently showed up? 

Regardless of what action button you press, the further left (not stacked) or lowest (stacked) button's selector is triggered.

**Comment by afollestad** [comment]
Another effect this pull request had is removing ripple selectors for API 21 and above. There's lots more to be done before a new release can come.

**Comment by afollestad** [comment]
I had to undo this pull request, there was too many things messed up unfortunately: the ripples on API 21 were removed, some weird selector bugs appeared, and support for using a Drawable instance and not just drawable resource IDs was missing. It shouldn't be too hard for me to do this though.

**Comment by afollestad** [comment]
I was able to quickly redo it, I explained here why selector customization was not included: https://github.com/afollestad/material-dialogs/issues/155

**Comment by afollestad** [comment]
Release 0.5.3 is now available.

**Comment by hzsweers** [comment]
@afollestad did you still want me to look into something related to this pull?

**Pull request merged**
