### PR TITLE
do not set app:hintEnabled and styles in md_dialog_stub_input

### LINKED ISSUE #1857: TextInputLayout clipped when adding textInputStyle
**Library Version:**
3.1.0 (tested with a2c743b15a3d4f37983b9e39c9fdb3656b0531a6 as well)
 
**Affected Device(s):**
Emulator Pixel 3 with Android Q Beta 5
 
**Describe the Bug:**
When adding a style to all text inputs via `textInputStyle`, the input box on the dialog is clipped. Adding a `TextInputLayout` to a non-dialog layout works fine.

**To Reproduce:**
1. checkout a2c743b15a3d4f37983b9e39c9fdb3656b0531a6 
2.  add `<item name="textInputStyle">@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox</item>` to `AppTheme` in the sample module
3. open a input dialog

image

When added to my app, it looks different but also clipped:

image

**Expected Behavior:**
The input box in a dialog should behave like all other `TextInputLayout` in the app. When setting  `textInputStyle` on the theme, the dialog should respect it.

image

---

This looks like #1707, #1701, #1695, #1712 and I am using *material 1.1.0-alpha08* but as mentioned, this happens in *1.0.0* as well (as used in the sample app).

### PR DESCRIPTION
**Pull request by hardysim**
Fixes #1857

### CODE REVIEW

**Comment by hardysim** [comment]
@afollestad seems like the travis script is broken. Can you have a look?

**Comment by afollestad** [comment]
@hardysim the build should work if you rebase on master now. Can you add a screenshot here too?

**Comment by hardysim** [comment]
Copied from https://github.com/afollestad/material-dialogs/issues/1857#issuecomment-515966496 to have some screenshots here as well:

> Looks like it can be fixed by just using the defaults of `TextInputLayout`. This means, removing `app:hintEnabled` and `style` from `TextInputLayout` and `TextInputEditText` in `md_dialog_stub_input.xml`.
> 
> This results in the known UI when not setting `textInputStyle`:
> 
> image
> 
> And when setting it, it uses the same style as all the other `TextInputLayout` in the app - which is what we want:
> 
> image
> 
> Hint: The missing horizontal margin on the box is fixed in `material 1.1.0-alpha08` so it should be fine to not set any margin manually.
> 
> image
> 
> ---
> 
> @afollestad why do we need `app:hintEnabled` and the styles `MD_Dialog_Input_Layout` and `MD_Dialog_Input_Layout.Message`? Did I miss something?

**Comment by hardysim** [comment]
@afollestad all green now

**Comment by afollestad** [comment]
Hmmm. The reason I apply `boxBackgroundColor` to the input style is so that the border does _not_ go all the way around the box. I'd rather have the correct defaults than force consumers to edit styles in their app.

**Comment by hardysim** [comment]
Yes this is some kind of philosophy question

I'd go with the defaults in a way which lets the theme decide how a input should look (hence, this PR) and your comment might relate to a default where inputs on dialogs should not have any border?

In my case, I have no way to style the input on the dialogs because this library does not offer any API for this AFAIK. 

So I suppose to not apply any styles (this PR) or add the possibility to set the style on the input. Which way do you want to go?

**Comment by hardysim** [comment]
When thinking of the original issue this PR tries to fix we first need to decide which way we want to go.

Currently, the border is broken / clipped. So it's a bug and we need to decide if following the theme style for the input is the way it should behave on dialogs as well. If yes, this PR is the solution.

If not, and inputs in dialogs should override the theme on inputs, we need a different fix for the current issue.

In the latter case, I'd love to have a way to override the override again to make inputs on dialogs look like any other input 😁

**Comment by hardysim** [comment]
@afollestad any updates / thoughts on this? If you can tell me how we want to handle this, I can update the PR (or maybe add functionality to change the theme manually).

**Pull request merged**
