### PR TITLE
Remove RadioButton background

### PR DESCRIPTION
**Pull request by darktiny**
Better fit material design's list dialog

### CODE REVIEW

**Comment by afollestad** [comment]
Thanks

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.4.1

**Comment by Silvuz** [comment]
how can i set the radio button now? i must use customView now?

https://www.google.com/design/spec/components/dialogs.html#

**Comment by afollestad** [comment]
@Silvuz no, it's still the same.

**Comment by Silvuz** [comment]
But the RadioButtom disappeared on 6.4.1. I must be doing something wrong. will recheck

**Pull request merged**
