### PR TITLE
Resolves #1752, ThreeTenBP is now included via 'implementation'.

### LINKED ISSUE #1752: Error while merging dex archives: Program type already present: org.threeten.bp.chrono.ChronoZonedDateTime$2
**Library Version:**

2.2.0
 
**Describe the Bug:**

Since the ThreeTenBP is included as 'api', the following error occurs when using this library (datetime) together with another library implementing the ThreeTenBP.

**To Reproduce:**
1. implementation 'org.threeten:threetenbp:1.3.8'
2. implementation 'com.jakewharton.threetenabp:threetenabp:1.2.0'
3. build project

**Expected Behavior:**

Everything should build though using those two libraries.

**Suggestion:**

use 'implementation' instead of 'api'.

### PR DESCRIPTION
**Pull request by guger**

### CODE REVIEW

**Comment by afollestad** [comment]
The only problem I see with this, is that using `api` allows consuming apps to see the classes that are used and returned by this library. E.g. in the callback or with methods like `selectedDate(): LocalDate`. If we remove that `api` reference, then consuming apps have to explicitly add the dependency to ThreetenBP if they don't already have it.

**Comment by guger** [comment]
Well, but that would only cost a line in the docs, but actually, users of the library are not able to use e.g. the ThreeTenABP library.
In my case, I need this lib, since the standard ThreeTenBP library causes an error 'No time-zone data files registered' on devices loading the time-zones of the ThreeTenBP lib too slow. ThreeTenABP provides another loading mechanims, which prevents this error.

**Comment by afollestad** [comment]
Right - maybe ThreeTenABP should be used here instead because of those reasons

**Comment by guger** [comment]
Well, sounds appropriate, since this is an android library.

**Comment by afollestad** [comment]
Alternatively, we could use `Calendar` and not require an external dependency 😄

**Comment by guger** [comment]
Okay!

**Pull request closed without merging**
